"""Smoke test for the REAL GAQA v1 data-creation pipeline (recovered from git).

Validates the original scripts without requiring the bioinformatics toolchain:
  - scripts/realval_v3_conditions.py  -> the real C01-C11 condition matrix
  - src/build_v3_manifest.py          -> 12 organisms, 9 train / 3 heldout
  - data/realval/manifest.csv         -> 12 rows + header (read URLs, RefSeq)
  - src/build_gaqa_dataset.py         -> render helpers produce the released schema
  - src/build_realval_dataset.py      -> QUAST/BUSCO/CheckM parsers present
  - src/build_gaqa_dataset_v3.py      -> rule labeling + jitter present
  - src/chunk_knowledge_sources.py, src/generate_knowledge_qa.py -> importable
  - env/realval.yml                  -> toolchain pinned

Usage: python data_pipeline/smoke_pipeline.py
"""
import importlib.util
import random
import sys
from pathlib import Path

DP = Path(__file__).resolve().parent
sys.path.insert(0, str(DP))  # enables `from src.* import ...`

PASS = []


def check(name, cond):
    assert cond, f"FAILED: {name}"
    PASS.append(name)


def load_script(name):
    spec = importlib.util.spec_from_file_location(name, DP / "scripts" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main():
    # 1) real condition matrix
    rv3 = load_script("realval_v3_conditions")
    conds = [c[0] for c in rv3.CONDITIONS]
    check("real conditions: 11", conds == [f"C{i:02d}" for i in range(1, 12)])
    check("real conditions: C01 10x clean low_coverage",
          rv3.CONDITIONS[0] == ("C01", 10, 0, None, "low_coverage", "default"))
    check("real conditions: C06 100x+10% distant contamination",
          rv3.CONDITIONS[5] == ("C06", 100, 10, "distant", "contamination", "default"))
    check("real conditions: C10 wrong k-mer / C11 MEGAHIT",
          rv3.CONDITIONS[9] == ("C10", 100, 0, None, "misassembly", "wrong")
          and rv3.CONDITIONS[10] == ("C11", 100, 0, None, "misassembly", "megahit"))

    # 2) real manifest (build_v3_manifest.py)
    from src import build_v3_manifest as bm
    orgs = bm.ORGANISMS
    check("real manifest: 12 organisms", len(orgs) == 12)
    splits = {o[7] for o in orgs}
    check("real manifest: train/heldout splits",
          splits == {"train", "heldout"}
          and sum(1 for o in orgs if o[7] == "heldout") == 3)
    check("real manifest: ecoli first, efaec last",
          orgs[0][0] == "ecoli" and orgs[-1][0] == "efaec")

    # 3) manifest.csv (read URLs + RefSeq references; the full file is
    #    regenerated by build_v3_manifest.py at runtime)
    csv_path = DP / "data" / "realval" / "manifest.csv"
    rows = [l for l in csv_path.read_text().splitlines() if l.strip()]
    check("manifest.csv: header present", rows[0].startswith("organism,"))
    check("manifest.csv: RefSeq URL format in rows",
          all("genomes/all/GCF" in l for l in rows[1:]))

    # 4) render helpers produce the released JSONL schema
    from src.build_gaqa_dataset import (render_metrics, make_input_text,
                                        make_question_output, assign_letters)
    rng = random.Random(42)
    metrics = {"N50": 300_000, "Genome fraction": 99.0, "BUSCO complete": 99.5,
               "BUSCO duplicated": 0.5, "Duplication ratio": 1.01,
               "# misassemblies": 1, "Total length": 4_600_000}
    text = render_metrics(metrics, rng)
    check("render_metrics: report text", "N50" in text and "BUSCO" in text)
    options = ["Acceptable quality", "Misassembly errors", "Low coverage", "Contamination"]
    letter = assign_letters(options, "Acceptable quality")
    check("assign_letters: finds correct letter", letter == "A")
    inp = make_input_text("qc_diagnosis", "Question text?", options)
    check("make_input_text: schema",
          inp.startswith("Subject: qc_diagnosis\nQuestion:") and "Options:\n" in inp)
    out = make_question_output("A", "Acceptable quality")
    check("make_question_output: gold", out == "The correct answer is A: Acceptable quality")

    # 5) builder: rule labeling + jitter present and functional
    from src.build_gaqa_dataset_v3 import rule_label, jitter_vector
    metrics = {"n50": 300_000, "largest_contig": 500_000, "total_length": 4_600_000,
               "num_contigs": 60, "gc_content_pct": 50.0,
               "busco_complete_pct": 99.5, "busco_duplicated_pct": 0.5,
               "busco_fragmented_pct": 0.0, "busco_missing_pct": 0.0,
               "checkm_completeness_pct": 99.0, "checkm_contamination_pct": 0.5,
               "genome_fraction_pct": 99.0, "num_misassemblies": 1,
               "mismatches_per_100kbp": 0.1, "sequencing_depth": 100}
    lab = rule_label(metrics, coverage=100.0)
    check("builder: rule_label returns valid label or None",
          lab is None or lab in ("acceptable", "misassembly",
                                 "contamination", "low_coverage"))
    jv = jitter_vector(metrics, rng, mag=0.10)
    check("builder: jitter within band", 0.85 <= jv["n50"] / 300_000 <= 1.15)

    # 6) realval parsers present
    from src import build_realval_dataset as brd
    for fn in ("parse_quast_report", "parse_busco_summary", "parse_checkm_qa",
               "load_conditions", "load_manifest"):
        check(f"realval parsers: {fn}", callable(getattr(brd, fn, None)))

    # 7) knowledge modules importable
    import src.chunk_knowledge_sources, src.generate_knowledge_qa
    check("knowledge modules import", True)

    # 8) conda env pinned
    yml = (DP / "env" / "realval.yml").read_text()
    check("env/realval.yml: bioinformatics tools pinned",
          all(t in yml for t in ("spades", "megahit", "quast", "busco", "checkm-genome",
                                 "seqtk", "flye")))

    print(f"\nREAL DATA-PIPELINE SMOKE TEST PASSED ({len(PASS)} checks)")


if __name__ == "__main__":
    main()